#!/usr/bin/env python3
"""
Train LSTM/XGBoost on Standard FLKS slopes (k=1..6)
=====================================================

Features: std_k1_slope, std_k2_slope, ..., std_k6_slope (6 features)
Target: oracle_label_macd_30m

Reads BTCUSD_flks_features.csv generated by prepare_flks_csv.py.
Same pipeline: chronological split 70/15/15, z-score from train, sequences 25.

Usage:
    python src/signal_processing/train_flks_slopes.py --model xgboost
    python src/signal_processing/train_flks_slopes.py --model lstm
"""

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).parent))
sys.path.insert(0, str(Path(__file__).parent.parent))
from constants import PREPARED_DATA_DIR

WINDOW = 25
SEED = 42
TRIM = 100


def main():
    parser = argparse.ArgumentParser(description='Train on Standard FLKS slopes')
    parser.add_argument('--model', default='xgboost', choices=['xgboost', 'lstm'])
    parser.add_argument('--window', type=int, default=WINDOW)
    parser.add_argument('--epochs', type=int, default=100)
    parser.add_argument('--seed', type=int, default=SEED)
    args = parser.parse_args()

    csv_path = f'{PREPARED_DATA_DIR}/BTCUSD_flks_features.csv'
    print(f"[1/5] Loading {csv_path} ...")
    df = pd.read_csv(csv_path, parse_dates=['datetime']).set_index('datetime').sort_index()
    print(f"       {len(df):,} rows")

    # Features: Standard FLKS slopes k=1..6
    feature_cols = [f'std_k{k}_slope' for k in range(1, 7)]
    label_col = 'oracle_label_macd_30m'

    missing = [c for c in feature_cols + [label_col] if c not in df.columns]
    if missing:
        print(f"ERROR: missing columns: {missing}")
        return

    cols_needed = feature_cols + [label_col]
    if 'close' in df.columns:
        cols_needed.append('close')
    df_clean = df[cols_needed].dropna()
    # Trim 100 at start and end
    df_clean = df_clean.iloc[TRIM:-TRIM]
    n = len(df_clean)
    n_feat = len(feature_cols)
    print(f"       {n:,} clean rows, {n_feat} features (trim {TRIM})")
    print(f"       Features: {feature_cols}")

    # Split chronological 70/15/15 with gap
    print(f"\n[2/5] Split + normalize ...")
    gap = args.window
    train_end = int(n * 0.70)
    val_end = int(n * 0.85)

    df_train = df_clean.iloc[:train_end - gap]
    df_val = df_clean.iloc[train_end:val_end - gap]
    df_test = df_clean.iloc[val_end:]
    print(f"       Train: {len(df_train):,} | Val: {len(df_val):,} | Test: {len(df_test):,}")

    # Z-score from train only
    stats = {}
    for col in feature_cols:
        mean = df_train[col].mean()
        std = df_train[col].std()
        if std < 1e-10:
            std = 1.0
        stats[col] = (mean, std)
        df_train[col] = (df_train[col] - mean) / std
        df_val[col] = (df_val[col] - mean) / std
        df_test[col] = (df_test[col] - mean) / std

    print(f"       Norm stats: {feature_cols[0]} mean={stats[feature_cols[0]][0]:.4f} "
          f"std={stats[feature_cols[0]][1]:.4f}")

    # Create sequences
    print(f"\n[3/5] Creating sequences (window={args.window}) ...")

    def make_sequences(df_split):
        features = df_split[feature_cols].values.astype(np.float32)
        labels = df_split[label_col].values.astype(np.int64)
        closes = df_split['close'].values.astype(np.float64) if 'close' in df_split.columns else None
        dates = df_split.index.values  # DatetimeIndex → numpy datetime64
        n_s = len(df_split)
        if n_s < args.window:
            empty_X = np.empty((0, args.window, n_feat), dtype=np.float32)
            empty_y = np.empty((0,), dtype=np.int64)
            empty_c = np.empty((0,), dtype=np.float64)
            empty_d = np.empty((0,), dtype='datetime64[ns]')
            return empty_X, empty_y, empty_c, empty_d
        indices = np.arange(args.window)[None, :] + np.arange(n_s - args.window + 1)[:, None]
        X = features[indices]
        y = labels[args.window - 1:]
        c = closes[args.window - 1:] if closes is not None else np.full(len(y), np.nan)
        d = dates[args.window - 1:]
        return X, y, c, d

    X_train, y_train, c_train, d_train = make_sequences(df_train)
    X_val, y_val, c_val, d_val = make_sequences(df_val)
    X_test, y_test, c_test, d_test = make_sequences(df_test)
    print(f"       Test dates: {d_test[0]} → {d_test[-1]}")
    print(f"       Train: {X_train.shape} | Val: {X_val.shape} | Test: {X_test.shape}")

    # Train
    if args.model == 'xgboost':
        print(f"\n[4/5] Training XGBoost ...")
        import xgboost as xgb

        X_tr_flat = X_train.reshape(len(X_train), -1)
        X_va_flat = X_val.reshape(len(X_val), -1)
        X_te_flat = X_test.reshape(len(X_test), -1)

        model = xgb.XGBClassifier(
            n_estimators=500, max_depth=6, learning_rate=0.05,
            subsample=0.8, colsample_bytree=0.8, min_child_weight=5,
            gamma=0.1, reg_alpha=0.1, reg_lambda=1.0,
            random_state=args.seed, eval_metric='logloss',
            early_stopping_rounds=20, n_jobs=-1,
        )
        model.fit(X_tr_flat, y_train, eval_set=[(X_va_flat, y_val)], verbose=50)

        train_acc = (model.predict(X_tr_flat) == y_train).mean()
        val_acc = (model.predict(X_va_flat) == y_val).mean()
        test_acc = (model.predict(X_te_flat) == y_test).mean()

        test_probs = model.predict_proba(X_te_flat)[:, 1]

        # Feature importance
        importances = model.feature_importances_
        flat_names = [f'k{(i % n_feat) + 1}_step{i // n_feat}' for i in range(args.window * n_feat)]
        indices = np.argsort(importances)[::-1]
        print(f"\n  Top 10 features:")
        for i in range(min(10, len(flat_names))):
            idx = indices[i]
            print(f"    {flat_names[idx]:<25} {importances[idx]:.4f}")

        model_path = f'models/xgboost_flks_std.json'
        Path('models').mkdir(exist_ok=True)
        model.save_model(model_path)

    else:  # lstm
        print(f"\n[4/5] Training LSTM ...")
        import torch
        import torch.nn as nn
        import torch.optim as optim
        from torch.utils.data import TensorDataset, DataLoader

        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        print(f"       Device: {device}")

        X_tr_t = torch.tensor(X_train, dtype=torch.float32)
        y_tr_t = torch.tensor(y_train, dtype=torch.float32)
        X_va_t = torch.tensor(X_val, dtype=torch.float32)
        y_va_t = torch.tensor(y_val, dtype=torch.float32)
        X_te_t = torch.tensor(X_test, dtype=torch.float32)
        y_te_t = torch.tensor(y_test, dtype=torch.float32)

        train_ds = TensorDataset(X_tr_t, y_tr_t)
        train_dl = DataLoader(train_ds, batch_size=128, shuffle=True)
        val_ds = TensorDataset(X_va_t, y_va_t)
        val_dl = DataLoader(val_ds, batch_size=256)

        class SimpleLSTM(nn.Module):
            def __init__(self, n_features, hidden=64, n_layers=2, dropout=0.2):
                super().__init__()
                self.lstm = nn.LSTM(n_features, hidden, n_layers,
                                    batch_first=True, dropout=dropout)
                self.fc = nn.Linear(hidden, 1)

            def forward(self, x):
                out, _ = self.lstm(x)
                return self.fc(out[:, -1, :]).squeeze(-1)

        model = SimpleLSTM(n_feat).to(device)
        optimizer = optim.Adam(model.parameters(), lr=0.0001)
        criterion = nn.BCEWithLogitsLoss()
        best_val_loss = float('inf')
        patience_counter = 0

        for epoch in range(args.epochs):
            model.train()
            train_loss = 0
            for xb, yb in train_dl:
                xb, yb = xb.to(device), yb.to(device)
                optimizer.zero_grad()
                pred = model(xb)
                loss = criterion(pred, yb)
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                optimizer.step()
                train_loss += loss.item() * len(xb)
            train_loss /= len(train_ds)

            model.eval()
            val_loss = 0
            with torch.no_grad():
                for xb, yb in val_dl:
                    xb, yb = xb.to(device), yb.to(device)
                    val_loss += criterion(model(xb), yb).item() * len(xb)
            val_loss /= len(val_ds)

            # Accuracy
            with torch.no_grad():
                train_pred = torch.sigmoid(model(X_tr_t.to(device))).cpu().numpy()
                val_pred = torch.sigmoid(model(X_va_t.to(device))).cpu().numpy()
            train_acc_e = ((train_pred > 0.5) == y_train).mean()
            val_acc_e = ((val_pred > 0.5) == y_val).mean()

            if (epoch + 1) % 5 == 0 or epoch == 0:
                print(f"  Epoch {epoch+1:>3}/{args.epochs} — "
                      f"Train loss={train_loss:.4f} acc={train_acc_e:.4f} | "
                      f"Val loss={val_loss:.4f} acc={val_acc_e:.4f}")

            if val_loss < best_val_loss:
                best_val_loss = val_loss
                patience_counter = 0
                torch.save(model.state_dict(), 'models/lstm_flks_std.pth')
            else:
                patience_counter += 1
                if patience_counter >= 10:
                    print(f"  Early stopping at epoch {epoch+1}")
                    break

        model.load_state_dict(torch.load('models/lstm_flks_std.pth', weights_only=True))
        model.eval()
        with torch.no_grad():
            train_acc = ((torch.sigmoid(model(X_tr_t.to(device))).cpu().numpy() > 0.5) == y_train).mean()
            val_acc = ((torch.sigmoid(model(X_va_t.to(device))).cpu().numpy() > 0.5) == y_val).mean()
            test_probs = torch.sigmoid(model(X_te_t.to(device))).cpu().numpy()
            test_acc = ((test_probs > 0.5) == y_test).mean()

    # Results
    print(f"\n[5/5] Results")
    print(f"{'=' * 50}")
    print(f"  Model: {args.model.upper()}")
    print(f"  Features: std_k1..k6_slope (6 × Standard FLKS)")
    print(f"  Train acc: {train_acc:.4f}")
    print(f"  Val acc:   {val_acc:.4f}")
    print(f"  Test acc:  {test_acc:.4f}")
    print(f"{'=' * 50}")

    # Save NPZ for analyze_predictions
    npz_path = f'{PREPARED_DATA_DIR}/macd_30m_dataset.npz'
    np.savez(npz_path,
             test_preds=test_probs,
             test_labels=y_test,
             test_closes=c_test,
             test_dates=d_test)
    print(f"  NPZ saved: {npz_path}")


if __name__ == '__main__':
    main()
