#!/usr/bin/env python3
"""
Concordance analysis from prepared CSV — no recalculation needed
================================================================

Reads the CSV generated by prepare_multitf_csv_aqkf.py and computes
sign concordance of Kalman filtered slope vs oracle label.

The CSV already contains:
  - macd_30m_filtered (AQ-KF Kalman position)
  - macd_30m_velocity (AQ-KF Kalman velocity)
  - oracle_label_macd_30m (pykalman.smooth label, 0/1)

We compute:
  - Slope from filtered: sign(filtered[t] - filtered[t-1])
  - Compare vs oracle_label
  - All samples + transitions only

This validates that the features given to the LSTM/XGBoost are
consistent with the FLKS tests.

Usage:
    python src/analyze_csv_concordance.py
"""

import numpy as np
import pandas as pd
from pathlib import Path
import argparse
import sys

sys.path.insert(0, str(Path(__file__).parent))
from constants import PREPARED_DATA_DIR

ASSET_CSV_MAP = {'BTC': 'BTCUSD'}


def main():
    parser = argparse.ArgumentParser(description='Concordance from prepared CSV')
    parser.add_argument('--indicator', default='macd')
    parser.add_argument('--timeframe', default='30m')
    args = parser.parse_args()

    ind = args.indicator
    tf = args.timeframe

    # Load CSV
    base = ASSET_CSV_MAP['BTC']
    csv_path = f'{PREPARED_DATA_DIR}/{base}_multitf_macd_rsi_cci.csv'
    print(f"Loading {csv_path} ...")
    df = pd.read_csv(csv_path, parse_dates=['datetime']).set_index('datetime').sort_index()
    print(f"  {len(df):,} rows")

    # Columns
    live_col = f'{ind}_{tf}_live'
    filt_col = f'{ind}_{tf}_filtered'
    vel_col = f'{ind}_{tf}_velocity'
    label_col = f'oracle_label_{ind}_{tf}'

    for col in [live_col, filt_col, label_col]:
        if col not in df.columns:
            print(f"ERROR: column {col} not found. Available: {list(df.columns)}")
            return

    print(f"  Columns: {live_col}, {filt_col}, {vel_col if vel_col in df.columns else 'N/A'}, {label_col}")

    # Drop NaN
    cols_needed = [live_col, filt_col, label_col]
    if vel_col in df.columns:
        cols_needed.append(vel_col)
    df_clean = df[cols_needed].dropna()
    n = len(df_clean)
    print(f"  Clean rows: {n:,}")

    live = df_clean[live_col].values
    filt = df_clean[filt_col].values
    oracle = df_clean[label_col].values.astype(int)

    # Compute slopes from filtered position
    # slope_filt[t] = filtered[t] - filtered[t-1]
    slope_filt = np.diff(filt, prepend=filt[0])
    pred_filt = (slope_filt > 0).astype(int)

    # Compute slopes from live
    slope_live = np.diff(live, prepend=live[0])
    pred_live = (slope_live > 0).astype(int)

    # Oracle transitions
    EPSILON = 1e-8
    oracle_transitions = np.zeros(n, dtype=bool)
    for i in range(1, n):
        if oracle[i] != oracle[i-1]:
            oracle_transitions[i] = True
    n_trans = oracle_transitions.sum()

    # Persistence
    oracle_persist = np.mean(oracle[1:] == oracle[:-1]) * 100

    print(f"\n{'=' * 70}")
    print(f"  CONCORDANCE FROM CSV — {ind.upper()}_{tf}")
    print(f"  Rows: {n:,} | Transitions: {n_trans:,} ({n_trans/n*100:.1f}%)")
    print(f"  Persistence: {oracle_persist:.1f}%")
    print(f"{'=' * 70}")

    # --- Concordance: filtered slope vs oracle ---
    valid = np.ones(n, dtype=bool)
    valid[0] = False  # first diff is meaningless

    all_match_filt = np.mean(pred_filt[valid] == oracle[valid]) * 100
    trans_match_filt = np.mean(pred_filt[valid & oracle_transitions] == oracle[valid & oracle_transitions]) * 100 if (valid & oracle_transitions).sum() > 0 else 0

    all_match_live = np.mean(pred_live[valid] == oracle[valid]) * 100
    trans_match_live = np.mean(pred_live[valid & oracle_transitions] == oracle[valid & oracle_transitions]) * 100 if (valid & oracle_transitions).sum() > 0 else 0

    print(f"\n  {'Method':<35} {'All':>8} {'Trans':>8}")
    print(f"  {'-' * 53}")
    print(f"  {'Persistence baseline':<35} {oracle_persist:>7.2f}% {'—':>8}")
    print(f"  {'Live slope sign(Δlive)':<35} {all_match_live:>7.2f}% {trans_match_live:>7.2f}%")
    print(f"  {'Filtered slope sign(Δfiltered)':<35} {all_match_filt:>7.2f}% {trans_match_filt:>7.2f}%")

    # --- Velocity sign vs oracle ---
    if vel_col in df.columns:
        vel = df_clean[vel_col].values
        pred_vel = (vel > 0).astype(int)
        all_match_vel = np.mean(pred_vel[valid] == oracle[valid]) * 100
        trans_match_vel = np.mean(pred_vel[valid & oracle_transitions] == oracle[valid & oracle_transitions]) * 100 if (valid & oracle_transitions).sum() > 0 else 0
        print(f"  {'Velocity sign(velocity > 0)':<35} {all_match_vel:>7.2f}% {trans_match_vel:>7.2f}%")

    # --- Split analysis (train/val/test) ---
    print(f"\n  --- Per split (70/15/15 chronological) ---")
    n_total = n
    train_end = int(n_total * 0.70)
    val_end = int(n_total * 0.85)

    splits = {
        'Train [0:70%]': (0, train_end),
        'Val [70:85%]': (train_end, val_end),
        'Test [85:100%]': (val_end, n_total),
    }

    print(f"  {'Split':<25} {'N':>8} {'Filt All':>9} {'Filt Trans':>11} {'Trans':>7}")
    print(f"  {'-' * 62}")

    for split_name, (s, e) in splits.items():
        sl = slice(s, e)
        n_split = e - s
        sl_valid = valid[sl]
        sl_oracle = oracle[sl]
        sl_pred = pred_filt[sl]
        sl_trans = oracle_transitions[sl]

        all_m = np.mean(sl_pred[sl_valid] == sl_oracle[sl_valid]) * 100
        n_t = sl_trans.sum()
        if (sl_valid & sl_trans).sum() > 0:
            trans_m = np.mean(sl_pred[sl_valid & sl_trans] == sl_oracle[sl_valid & sl_trans]) * 100
        else:
            trans_m = 0
        print(f"  {split_name:<25} {n_split:>8,} {all_m:>8.2f}% {trans_m:>10.2f}% {n_t:>7,}")

    print(f"  {'-' * 62}")
    print(f"{'=' * 70}")
    print("Done.")


if __name__ == '__main__':
    main()
